language: rust
rust:
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - curl -L https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d $HOME/protoc
env:
  - PATH=$HOME/protoc/bin:$PATH
script:
  - cargo build --verbose --all
